### ISSUE TITLE
Crash upon answering first ping

### ISSUE THREAD

**Issue by dreeves** [mykter/TagTime-desktop#124]
![image](https://user-images.githubusercontent.com/9928/34232344-ba58adfe-e594-11e7-9592-a134f2a7cd16.png)

This is macOS Sierra.

**Comment by mykter** [comment]
Thanks for testing it out.

Looks like Travis is also Sierra and doesn't hit it. I suspected we'd hit things like this when it got onto human-powered macs!

If you launch it from a terminal I think we should get more detailed information when it crashes. Or if you want to directly test it, the steps are:
* git clone ...
* npm install
* npm build
* npm test

**Comment by elkcip** [comment]
Same error here. Running El Capitan 10.11.6.

Output when launched from a terminal:

`$ /Applications/TagTime-desktop.app/Contents/MacOS/TagTime-desktop
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2018:01:09T16:01, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:324:94)
    at configFromString (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:2366:11)
    at configFromInput (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:2592:9)
    at prepareConfig (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:2575:9)
    at createFromConfig (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:2542:40)
    at createLocalOrUTC (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:2629:12)
    at createLocal (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:2633:12)
    at hooks (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/node_modules/moment/moment.js:16:25)
    at new PingTimes (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/app/src/pingtimes.js:21:33)
    at main (/Applications/TagTime-desktop.app/Contents/Resources/app.asar/app/src/main-process/main.js:195:20)
warn: Could not parse entry: ''`

**Comment by mykter** [comment]
Thanks. I've recently got access to a Mac so should be able to have a look this weekend.

**Comment by mykter** [comment]
It was a simple bug in the first run code. Unfortunately I don't have tests for that path. I'll test it out and if all is well release v0.6.0 shortly.

**Comment by mykter** [comment]
Released v0.6.0 with the fix. Hopefully the tray icon isn't terrible now either!
