### ISSUE TITLE
ElectronStore failure when running from AppImage

### ISSUE THREAD

**Issue by mykter** [mykter/TagTime-desktop#138]
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOTDIR: not a directory, mkdir '/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/devconfig'
    at Object.fs.mkdirSync (fs.js:891:18)
    at make (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/node_modules/make-dir/index.js:59:12)
    at Function.module.exports.sync (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/node_modules/make-dir/index.js:82:9)
    at ElectronStore.get store [as store] (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/node_modules/conf/index.js:120:13)
    at ElectronStore.Conf (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/node_modules/conf/index.js:44:56)
    at ElectronStore (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/node_modules/electron-store/index.js:20:3)
    at new Config (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/app/src/main-process/config.js:71:21)
    at main (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/app/src/main-process/main.js:195:21)
    at Object.<anonymous> (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/app/src/main-process/main.js:233:5)
    at Object.<anonymous> (/tmp/.mount_TagTim7rAbd9/app/resources/app.asar/app/src/main-process/main.js:237:3)
```

**Comment by mykter** [comment]
That fixed it
