### ISSUE TITLE
7z ENOENT prior to creating tray on Windows

### ISSUE THREAD

**Issue by mykter** [mykter/TagTime-desktop#81]
debug: TagTime-desktop ready
error:  Error: spawn C:\Users\mmacnair\AppData\Local\Programs\TagTime-desktop\resources\app.asar\node_modules\7zip\7zip-lite\7z.exe ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
debug: Creating tray

**Comment by mykter** [comment]
Now it looks like this, and the tray doesn't appear.
```
error:  Error: spawn C:\Users\mmacnair\AppData\Local\Programs\TagTime-desktop\re
sources\app.asar\node_modules\7zip\7zip-lite\7z.exe ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): TypeError: Error processing argument at index 0, conversion failure
 from C:\Users\mmacnair\AppData\Local\Programs\TagTime-desktop\resources\app.asa
r\resources\tagtime.ico
(node:1368) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```
